name: package-check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6

      - name: setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # pin@v6
        with:
          node-version-file: .node-version
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run bundle

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ -n "$(git status --porcelain -- dist/)" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git status --short dist/
            git diff
            exit 1
          fi
        id: diff

      # If index.js was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # pin@v7
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
