name: test
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v6
        with:
          persist-credentials: false

      - name: setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # pin@v6
        with:
          node-version-file: .node-version
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: test
        run: npm run ci-test
