name: Update Latest Release Tag
run-name: Update ${{ github.event.inputs.major_version_tag }} with ${{ github.event.inputs.source_tag }}

on:
  workflow_dispatch:
    inputs:
      source_tag:
        description: 'The tag or reference to use as the source (example: v8.0.0)'
        required: true
        default: vX.X.X
      major_version_tag:
        description: 'The major release tag to update with the source (example: v8)'
        required: true
        default: vX

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: tag new target
        run: git tag -f ${{ github.event.inputs.major_version_tag }} ${{ github.event.inputs.source_tag }}

      - name: push new tag
        run: git push origin ${{ github.event.inputs.major_version_tag }} --force
